### ISSUE TITLE
detekt-cli not found

### ISSUE THREAD

**Issue by astelmachonak-nydig** [peter-murray/setup-detekt#2]
I am using latest version of this action and in some cases (not always) getting the following issue:

![image](https://user-images.githubusercontent.com/100310178/175355890-fcbe99b3-1b67-4fd7-a253-f301ca4fc41d.png)

It says "adding to path" and when I try to run it I got "detekt-cli: command not found". Any ideas? Going to try using full path for `detekt-cli` instead as a workaround.

**Comment by astelmachonak-nydig** [comment]
@peter-murray I got some more details about the issue - looks like it happens when detekt-cli is found in the tools cache on the build node, but the location for binary is not properly detected:

This is setup-detekt action with wrong PATH to detekt binary returned:

![image](https://user-images.githubusercontent.com/100310178/187821973-686cc0eb-1299-46f6-a1f0-400b7ab66aa5.png)

And here is the structure of the directories under `/home/ec2-user/actions-runner/_work/_tool/detekt-cli/1.21.0`:

![image](https://user-images.githubusercontent.com/100310178/187822293-205ac2bd-857e-4d89-a580-87f5a8c2e5ed.png)

So, the correct detekt path is this case is `/home/ec2-user/actions-runner/_work/_tool/detekt-cli/1.21.0/all/detekt-cli-1.21.0/bin/detekt-cli`, but the action returns `/home/ec2-user/actions-runner/_work/_tool/detekt-cli/1.21.0/all/bin/detekt-cli`. 

Any ideas why this happening?

**Comment by peter-murray** [comment]
Thank you @astelmachonak-nydig that helped in diagnosing the issue. The path returned from the tool cache was not being modified to include the nesting directory that it does include when it resolves from the release archives.

I have updated version `v2` of the action to fix this. It should work properly now under that circumstance.

**Comment by astelmachonak-nydig** [comment]
Thanks for the quick fix! Will check it out today and report back.

**Comment by astelmachonak-nydig** [comment]
Looks good on my end, thanks again for the fix!
